version: "3"
services:
  snapdrop-server:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
  snapdrop:
    image: "nginx:alpine"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - FQDN=localhost
    # env_file: ./docker/fqdn.env
    # entrypoint: /mnt/openssl/create.sh
    command: ["nginx", "-g", "daemon off;"]
networks:
  default:
    name: keldonet